# ==============================================================================
# PERFIL: EXTREME PERFORMANCE - CONFIGURAÇÕES ULTRA-AVANÇADAS
# ==============================================================================
# Baseado na documentação oficial ThingsBoard + análise de gargalos
# Foco: CPU 472% -> targeting <200% através de configurações extremas
# ==============================================================================

# === RPC CONFIGURATION (ULTRA-EXTREMA) ===
CLIENT_SIDE_RPC_TIMEOUT: 100

# === ACTOR SYSTEM OPTIMIZATION (CRÍTICA) ===
ACTORS_SYSTEM_THROUGHPUT: 10
ACTORS_SYSTEM_DEVICE_DISPATCHER_POOL_SIZE: 8
ACTORS_SYSTEM_RULE_DISPATCHER_POOL_SIZE: 16
ACTORS_RULE_DB_CALLBACK_THREAD_POOL_SIZE: 20

# === HTTP OPTIMIZATION (MÁXIMA) ===
HTTP_REQUEST_TIMEOUT_MS: 500
HTTP_MAX_CONNECTIONS: 1000
HTTP_MAX_CONNECTIONS_PER_ROUTE: 200
HTTP_CONNECTION_TIMEOUT_MS: 250
HTTP_SOCKET_TIMEOUT_MS: 500

# === BATCH PROCESSING (MÍNIMO ABSOLUTO) ===
SQL_TS_BATCH_SIZE: 5000
SQL_TS_BATCH_MAX_DELAY_MS: 2
SQL_TS_LATEST_BATCH_SIZE: 2000
SQL_TS_LATEST_BATCH_MAX_DELAY_MS: 1
SQL_TS_BATCH_THREADS: 5
SQL_TS_LATEST_BATCH_THREADS: 5
SQL_TS_CALLBACK_THREAD_POOL_SIZE: 24

# === QUEUE OPTIMIZATION (MÁXIMA CONCORRÊNCIA) ===
TB_QUEUE_CORE_POLL_INTERVAL_MS: 1
TB_QUEUE_CORE_PARTITIONS: 20
TB_QUEUE_CORE_WORKERS: 32
TB_QUEUE_RULE_ENGINE_THREAD_POOL_SIZE: 128
TB_QUEUE_TRANSPORT_THREAD_POOL_SIZE: 128
TB_QUEUE_JS_THREAD_POOL_SIZE: 64
TB_QUEUE_RULE_ENGINE_POLL_INTERVAL_MS: 1

# === JVM OPTIMIZATION (ULTRA-EXTREMA - baseado em 15GB RAM) ===
JAVA_OPTS: "-Xms10g -Xmx12g -XX:+UseG1GC -XX:MaxGCPauseMillis=5 -XX:G1HeapRegionSize=32m -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:G1NewSizePercent=60 -XX:G1MaxNewSizePercent=80 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:+AlwaysPreTouch -XX:+AggressiveOpts -server"

# === DATABASE CONNECTION POOL OPTIMIZATION ===
SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 32

# === MQTT OPTIMIZATION (BAIXÍSSIMA LATÊNCIA) ===
MQTT_TIMEOUT_MS: 1000
NETTY_WORKER_GROUP_THREADS: 24
NETTY_BOSS_GROUP_THREADS: 2

# === PERFIL INFO ===
PROFILE_NAME: "Extreme Performance URLLC"
PROFILE_DESCRIPTION: "Configuração extrema - RPC 100ms, actors otimizados, JVM 12GB, GC 5ms"
HEARTBEAT_INTERVAL: 1
