# ==============================================================================
# PERFIL: TEST #5 - MELHOR PERFORMANCE GERAL
# ==============================================================================
# Baseado em: Test #5 - melhor S2M (175-290ms) e M2S (130-150ms)
# ODTE: 0.88 (excelente)
# Conectividade: Alta
# ==============================================================================

# === THINGSBOARD CORE CONFIGURATION ===
SERVER_DATASOURCES_DEFAULT_BATCH_SIZE: 200
SERVER_DATASOURCES_DEFAULT_BATCH_MAX_DELAY_MS: 25

# === RPC CONFIGURATION (BALANCEADA) ===
CLIENT_SIDE_RPC_TIMEOUT: 1000

# === HTTP OPTIMIZATION (MODERADA) ===
HTTP_REQUEST_TIMEOUT_MS: 3000
HTTP_MAX_CONNECTIONS: 300
HTTP_MAX_CONNECTIONS_PER_ROUTE: 75
HTTP_CONNECTION_TIMEOUT_MS: 750
HTTP_SOCKET_TIMEOUT_MS: 1500

# === BATCH PROCESSING OPTIMIZATION ===
SQL_TS_BATCH_SIZE: 1000
SQL_TS_BATCH_MAX_DELAY_MS: 10
SQL_TS_LATEST_BATCH_SIZE: 500
SQL_TS_LATEST_BATCH_MAX_DELAY_MS: 5

# === QUEUE OPTIMIZATION BALANCEADA ===
TB_QUEUE_CORE_POLL_INTERVAL_MS: 15
TB_QUEUE_CORE_PARTITIONS: 6
TB_QUEUE_CORE_WORKERS: 12
TB_QUEUE_RULE_ENGINE_THREAD_POOL_SIZE: 10
TB_QUEUE_TRANSPORT_THREAD_POOL_SIZE: 8

# === JVM OPTIMIZATION ===
JAVA_OPTS: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -server"

# === MQTT OPTIMIZATION ===
MQTT_TIMEOUT_MS: 7000
MQTT_KEEP_ALIVE_SECONDS: 30

# === PERFIL INFO ===
PROFILE_NAME: "Test #5 - Best Performance"
PROFILE_DESCRIPTION: "Configuração baseada no Test #5 com melhor performance S2M/M2S"
HEARTBEAT_INTERVAL: 4
