version: "3.9"

services:
  thingsboard:
    image: thingsboard/tb-postgres
    container_name: tb-main
    environment:
      TB_QUEUE_TYPE: in-memory
    ports:
      - "8080:9090"  # Porta externa 8080 acessa o ThingsBoard na 9090
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb-main
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=middts
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin_token_middts
    volumes:
      - influxdb_data:/var/lib/influxdb2

  middts:
    build:
      context: middts
    container_name: middts-main
    depends_on:
      - db
      - influxdb
    ports:
      - "8000:8000"
    env_file:
      - ./middts/.env
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres-main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: middts
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  iot_simulator_1:
    build:
      context: simulator
    container_name: simulator-1
    environment:
      DEVICE_ID: device_sim_001
      DJANGO_SETTINGS_MODULE: iot_simulator.settings
    depends_on:
      - thingsboard
      - middts
    restart: unless-stopped

volumes:
  tb-data:
  tb-logs:
  influxdb_data:
  pg_data:
