# ThingsBoard Configuration - Optimized for URLLC
# ================================================
# Configuração otimizada para Ultra-Reliable Low Latency Communication (URLLC)
# Reduz timeouts e delays para atingir latência <1ms

# === RPC TIMEOUT CONFIGURATION ===
# ULTRA-agressivo para URLLC: reduzido para 50ms target extremo
CLIENT_SIDE_RPC_TIMEOUT: 50

# === DATABASE BATCH PROCESSING ===
# ULTRA-reduzido delays de batch para latência mínima
SQL_TS_BATCH_MAX_DELAY_MS: 5       # Reduzido de 10ms para 5ms
SQL_TS_LATEST_BATCH_MAX_DELAY_MS: 2  # Reduzido de 5ms para 2ms

# === CASSANDRA (LEGACY - MANTIDO PARA COMPATIBILIDADE) ===
CASSANDRA_TS_BATCH_MAX_DELAY_MS: 5
CASSANDRA_TS_LATEST_BATCH_MAX_DELAY_MS: 2

# === PERFORMANCE TUNING ===
# Configurações adicionais para alta performance URLLC
DEFAULT_TOKEN_EXPIRATION_TIME: 10800  # 3 hours
REFRESH_TOKEN_EXPIRATION_TIME: 86400  # 24 hours

# === HTTP CONNECTION POOL OPTIMIZATION ===
# Otimizar connection pool para reduzir latência de RPC calls
HTTP_REQUEST_TIMEOUT_MS: 30000
HTTP_MAX_CONNECTIONS: 200
HTTP_MAX_CONNECTIONS_PER_ROUTE: 50
HTTP_CONNECTION_TIMEOUT_MS: 3000    # 3s timeout para estabelecer conexão
HTTP_SOCKET_TIMEOUT_MS: 3000        # 3s timeout para socket read

# === THREAD POOL OPTIMIZATION ===
# Mais threads para paralelizar RPC processing
ACTORS_SYSTEM_MAX_ACTOR_INIT_ATTEMPTS: 3
ACTORS_SYSTEM_MAX_ACTOR_MAILBOX_SIZE: 1000

# === QUEUE OPTIMIZATION ===
# Reduzir delays no processamento de filas
TB_QUEUE_CORE_ADMIN_NOTIFICATION_POLL_INTERVAL_MS: 100
TB_QUEUE_CORE_STATS_PRINT_INTERVAL_MS: 60000

# === MAIL CONFIGURATION (DISABLED) ===
MAIL_ENABLED: false

# === DATABASE CONFIGURATION ===
# Use PostgreSQL por padrão
SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

# === LOGGING ===
# Configuração de log otimizada para debugging de performance
LOGGING_LEVEL_ROOT: INFO
LOGGING_LEVEL_COM_THINGSBOARD: INFO

# === CACHE CONFIGURATION ===
# Otimizar cache para reduzir latência
CACHE_TYPE: caffeine
CACHE_SPECS_RELATIONS: maximumSize=100000,expireAfterWrite=3600s

# === QUEUE CONFIGURATION ===
TB_QUEUE_TYPE: in-memory
TB_QUEUE_IN_MEMORY_STATS_PRINT_INTERVAL_MS: 60000

# === HTTP/HTTPS CONFIGURATION ===
HTTP_ENABLED: true
HTTPS_ENABLED: false
HTTP_BIND_ADDRESS: 0.0.0.0
HTTP_BIND_PORT: 8080

# === MQTT CONFIGURATION ===
MQTT_ENABLED: true
MQTT_BIND_ADDRESS: 0.0.0.0
MQTT_BIND_PORT: 1883
MQTT_TIMEOUT: 10000

# === COAP CONFIGURATION ===
COAP_ENABLED: true
COAP_BIND_ADDRESS: 0.0.0.0
COAP_BIND_PORT: 5683
COAP_TIMEOUT: 10000

# === LWM2M CONFIGURATION ===
LWM2M_ENABLED: false

# === SNMP CONFIGURATION ===
SNMP_ENABLED: false

# === SECURITY ===
SECURITY_ENABLED: true

# === INSTALLATION ===
INSTALL_TB: true
LOAD_DEMO: true

# === JVM CONFIGURATION ===
JAVA_OPTS: "-Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=20"